<a href="https://colab.research.google.com/github/umasankari11/Python-Concepts/blob/main/Data_Analysis_using_NumPy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**I. Numpy Array Operations:**

**Problem Statement:**

To learn how to use NumPy for creating arrays, performing basic
array operations, and conducting numerical computations through analyzing
temperature data.

**Scenario:**
You are given a list of daily average temperatures (in degrees Celsius)
recorded over two weeks. Your task is to use NumPy to analyze this data.

**Step wise Instructions:**

**1. Create a 1D NumPy Array:**

Create a 1D NumPy array named temperatures_w1 for Week 1 with the
following values:
[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]



In [ ]:
#Import Numpy

import numpy as np

In [ ]:
#Answer :

#1. Create a 1D NumPy Array (Week 1)

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print("Week 1 Temperatures:", temperatures_w1)

Week 1 Temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]


**2. Inspection and Properties:**

● Inspect the shape, data type, and the number of elements in the array.
Inspect the shape of the temperatures_w1 array.

In [ ]:
#Answer :

# 2. Inspection and Properties

print("Week 1 Temperatures:", temperatures_w1)
print("Shape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)

Week 1 Temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Shape: (7,)
Data Type: float64
Number of Elements: 7


**3. Array Operations:**

1. Convert the temperatures_w1 from Celsius to Fahrenheit using the
formula: Fahrenheit = (Celsius * 9/5) + 32
2. Find the maximum, minimum, and mean temperatures for the week.



In [ ]:
#3. Array Operations

#1. Convert Celsius → Fahrenheit

temperatures_f = (temperatures_w1 * 9/5) + 32

print("\n Temperatures in Fahrenheit:", temperatures_f)

#2. Find Max, Min & Mean

print("\n Maximum Temperature:", np.max(temperatures_w1))

print("\n Minimum Temperature:", np.min(temperatures_w1))

print("\n Mean Temperature:", np.mean(temperatures_w1))


 Temperatures in Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]

 Maximum Temperature: 26.1

 Minimum Temperature: 20.8

 Mean Temperature: 23.542857142857144


**4. Array Slicing and Indexing:**
1. Extract the temperatures for the first three days of the week.

2. Extract the temperatures for the weekend (last two days).

3. Extract the temperatures for the middle three days of the week.



In [ ]:
# 4. Array Slicing & Indexing

# 1. Extract the temperatures for the first three days of the week

first_three = temperatures_w1[:3]

print("\n First 3 Days:", first_three)

# 2. Extract the temperatures for the weekend (last two days)

weekend = temperatures_w1[-2:]

print("\n Weekend Temperatures:", weekend)

# 3. Extract the temperatures for the middle three days of the week.

middle_three = temperatures_w1[2:5]

print("\n Middle 3 Days:", middle_three)


 First 3 Days: [22.5 25.3 20.8]

 Weekend Temperatures: [24.8 21.9]

 Middle 3 Days: [20.8 23.4 26.1]


**5. Create a 2D Array:**

Create a 2D NumPy array named temperatures where each row represents
temperatures for a different week:

★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)

★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)



In [ ]:
#5. Create a 2D Array for 2 Weeks
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],  # Week 1
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]   # Week 2
])

print("2D Temperature Array:\n\n", temperatures)

2D Temperature Array:

 [[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


**6. Inspect and Slice the 2D Array:**

1. Inspect and print the shape, data type, and total number of elements in the
temperatures array.

2. Extract the temperatures for each week and the weekends (last two days)
for both weeks.

In [ ]:
# 6. Inspect & Slice the 2D Array
# 1. Inspection

print("--------2D Temperature Array:-------------\n\n", temperatures)

print("\n --------Shape, Data Type, Total Number of Elements in the Temperatures Array---------------\n")

print("\n Shape:", temperatures.shape)
print("\n Data Type:", temperatures.dtype)
print("\n Total Elements:", temperatures.size)

# 2.1 Extract temperatures for each week
week1 = temperatures[0]

week2 = temperatures[1]

print("\n ----------Temperatures for each week---------")

print("\n Week 1:", week1)
print("\n Week 2:", week2)

# 2.2 Extract weekend temperatures (last 2 days) for both weeks

print("\n ----------Temperatures for last 2 Days---------\n")

weekend_week1 = week1[-2:]
weekend_week2 = week2[-2:]

weekends_both = temperatures[:, -2:]

print("\n Weekend Temperatures for Both Weeks:\n\n", weekends_both)

--------2D Temperature Array:-------------

 [[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

 --------Shape, Data Type, Total Number of Elements in the Temperatures Array---------------


 Shape: (2, 7)

 Data Type: float64

 Total Elements: 14

 ----------Temperatures for each week---------

 Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]

 Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]

 ----------Temperatures for last 2 Days---------


 Weekend Temperatures for Both Weeks:

 [[24.8 21.9]
 [22.8 20.1]]


**II. Pandas Series:**

**1. Creating Pandas Series:**

● Create a Pandas Series named marks with the following data:
➢ Marks: 95, 92, 89, 85, 80
➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'



In [ ]:
#Import Numpy

import pandas as pd

In [ ]:
#1. Creating Pandas Series:
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print("\n Marks Series:\n", marks)


 Marks Series:
 Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


**2. Indexing and Slicing:**

1. Use the integer index position to access the mark of the 1st rank student.

2. Use the loc accessor to retrieve the marks of the top 3 ranks by
specifying their index labels.

3. Use the iloc accessor to retrieve the mark of the 3rd rank student.

4. Apply a boolean mask to filter the Series and retrieve the ranks where the
marks are greater than 90.


In [ ]:
# 1. Access mark of 1st rank student using integer index

# (1st element → index position 0)

marks_first_rank = marks.iloc[0]

print("--1. Access mark of 1st rank student using integer index--")

print("\n Mark of 1st Rank Student (integer index):", marks_first_rank)

#2. Retrieve top 3 ranks using .loc

# Using custom labels:

print("\n--2. Retrieve top 3 ranks using .loc--\n")

top_3_marks = marks.loc[['Rank1', 'Rank2', 'Rank3']]

print("Top 3 Ranks (loc):\n", top_3_marks)

#3. Retrieve mark of 3rd rank using .iloc

print("\n--3. Retrieve mark of 3rd rank using .iloc--\n")

rank3_mark = marks.iloc[2]

print("\n Mark of 3rd Rank Student (iloc):", rank3_mark)

#4. Apply boolean mask → marks greater than 90

marks_above_90 = marks[marks > 90]

print("\n--4. Apply boolean mask--\n")

print("\n Ranks with Marks > 90:\n", marks_above_90)

--1. Access mark of 1st rank student using integer index--

 Mark of 1st Rank Student (integer index): 95

--2. Retrieve top 3 ranks using .loc--

Top 3 Ranks (loc):
 Rank1    95
Rank2    92
Rank3    89
dtype: int64

--3. Retrieve mark of 3rd rank using .iloc--


 Mark of 3rd Rank Student (iloc): 89

--4. Apply boolean mask--


 Ranks with Marks > 90:
 Rank1    95
Rank2    92
dtype: int64


**3. Manipulating Series:**

1. Modify the mark of the student with the 1st rank to 100.

2. Remove the entry corresponding to the last rank from the Series.

3. Compute the CGPA by dividing each mark in the Series by 10.

In [ ]:
#Manipulating the Series
#1. Modify mark of 1st rank to 100
marks['Rank1'] = 100
print("\n --Modify mark of 1st rank to 100--")
print("After Updating Rank1 to 100:\n", marks)

#2. Remove entry of last rank (Rank5)

print("\n --Remove entry of last rank (Rank5)--\n")

marks = marks.drop('Rank5')
print("After Removing Last Rank:\n", marks)

#3. Compute CGPA = marks / 10

cgpa = marks / 10

print("\n --Compute CGPA--\n ")

print("CGPA Series:", cgpa)


 --Modify mark of 1st rank to 100--
After Updating Rank1 to 100:
 Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

 --Remove entry of last rank (Rank5)--

After Removing Last Rank:
 Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

 --Compute CGPA--
 
CGPA Series: Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


**III. Pandas DataFrame:**

1. Creating Pandas DataFrame:

● Create a Pandas DataFrame named transactions with the following data:

1. TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110
2. ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
3. Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North'
4.  Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400



In [ ]:
#import pandas

import pandas as pd

# 1. Creating the DataFrame.

transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture',
                        'Clothing', 'Electronics', 'Furniture', 'Clothing',
                        'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North',
               'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print("Transactions DataFrame:\n", transactions)

Transactions DataFrame:
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


**2. Data Exploration:**

1. Display the transactions DataFrame and its basic information, including
head, tail, shape, column names, and data types.
2. Display only the 'ProductCategory' and 'Amount' columns.
3. Retrieve the last 3 columns of the DataFrame using iloc or loc.
4. Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.
5. Find the value counts for the 'ProductCategory' column.
6. Find the unique values in the 'Region' column.
7. Group by 'Region' and find the mean amount for each region.


In [ ]:
#1. Display DataFrame, head, tail, shape, columns, dtypes

print("Full DataFrame:\n", transactions)

print("\nHead (first 5 rows):\n", transactions.head())
print("\nTail (last 5 rows):\n", transactions.tail())

print("\nShape (rows, columns):", transactions.shape)
print("\nColumn Names:", transactions.columns.tolist())
print("\nData Types:\n", transactions.dtypes)

Full DataFrame:
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Head (first 5 rows):
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Tail (last 5 rows):
    TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Fur

In [ ]:
#2. Display only 'ProductCategory' and 'Amount' columns

prod_amount = transactions[['ProductCategory', 'Amount']]

print("\nProductCategory and Amount:\n", prod_amount)


ProductCategory and Amount:
   ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [ ]:
#3. Retrieve the last 3 columns using iloc

last_3_cols = transactions.iloc[:, -3:]

print("\nLast 3 Columns:\n", last_3_cols)


Last 3 Columns:
   ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [ ]:
#4. Filter rows where Region == 'North' and Amount > 200

filtered_rows = transactions[(transactions['Region'] == 'North') &
                             (transactions['Amount'] > 200)]
print("\n----Rows where Region = 'North' and Amount > 200:-----\n\n", filtered_rows)


----Rows where Region = 'North' and Amount > 200:-----

    TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [ ]:
#5. Value counts for 'ProductCategory'

product_counts = transactions['ProductCategory'].value_counts()

print("\n-----Value Counts for ProductCategory:-------\n\n", product_counts)



-----Value Counts for ProductCategory:-------

 ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [ ]:
#6. Unique values in 'Region'

unique_regions = transactions['Region'].unique()

print("\nUnique Regions:\n\n", unique_regions)


Unique Regions:

 ['North' 'South' 'East' 'West']


In [ ]:
#7. Group by 'Region' and find mean Amount for each region

region_mean_amount = transactions.groupby('Region')['Amount'].mean()

print("\nMean Amount by Region:\n", region_mean_amount)


Mean Amount by Region:
 Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


**3. Manipulating the DataFrame:**

1. Modify the 'Amount' for the transaction with TransactionID 102 to 165.
2. Add a new column 'Discount' by calculating 10% of the 'Amount'.
3. Remove the row with TransactionID 109.
4. Delete the 'Discount' column from the DataFrame.

In [ ]:
#1. Modify Amount for TransactionID == 102 to 165

transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

print("\nAfter Updating Amount for TransactionID 102:\n", transactions)


After Updating Amount for TransactionID 102:
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400


In [ ]:
#2. Add new column 'Discount' = 10% of Amount

transactions['Discount'] = transactions['Amount'] * 0.10

print("\nAfter Adding Discount Column:\n", transactions)


After Adding Discount Column:
    TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [ ]:
#3. Remove the row with TransactionID == 109

transactions = transactions[transactions['TransactionID'] != 109]

print("\nAfter Removing TransactionID 109:\n", transactions)


After Removing TransactionID 109:
    TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [ ]:
#4. Delete the 'Discount' column

transactions = transactions.drop(columns=['Discount'])

print("\nAfter Dropping Discount Column:\n\n", transactions)


After Dropping Discount Column:

    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
