<a href="https://colab.research.google.com/github/umasankari11/Python-Concepts/blob/main/Session11_Numpy_Concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Tutorial – Arrays, Operations, and Functions**

**Installation**- `!pip install numpy`

## 🧩 **Setup**

```python
import numpy as np
```

---

# 📘 **1. Introduction to NumPy**

## **What is NumPy?**

NumPy (Numerical Python) is a Python library for performing fast numerical computations.
It introduces the **ndarray**, a fast and memory-efficient multidimensional array.

---

# 📗 **2. Creating NumPy Arrays**

## **2.1 List → Array**



In [ ]:
import numpy as np
l1=[23.4,5.0,3.8,533,8953]
arr1=np.array(l1)
print(f"Numpy array={arr1}\n Datatype={type(arr1)}")

Numpy array=[2.340e+01 5.000e+00 3.800e+00 5.330e+02 8.953e+03]
 Datatype=<class 'numpy.ndarray'>



## **2.2 2D Array**

In [ ]:
arr_2D=np.array([[22,14,35],
                 [56,199,208]])
arr_2D

array([[ 22,  14,  35],
       [ 56, 199, 208]])

## **2.3 Array Attributes**


In [ ]:
#number of dimension
arr1.ndim


1

In [ ]:
# check how many rows and columns
arr1.shape
arr_2D.shape


(2, 3)

In [ ]:
# number of elements in array
arr1.size
arr_2D.size

6

In [ ]:
arr1.dtype

dtype('float64')

# 📙 **3. Creating Arrays Using NumPy Functions**

## **3.1 Zeros, Ones, Full**

In [ ]:
#zero array
zero_arr=np.zeros((3,4))
zero_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#ones array using ones()--2rows,6cols
ones_arr=np.ones((3,4),dtype='int')
ones_arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
# full()
full_arr=np.full((4,2),3)
full_arr

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

## **3.2 Ranges**

In [ ]:
     # like Python range

np.arange(3,30,3)


array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
    # 5 evenly spaced points
np.linspace(0,10,3)

array([ 0.,  5., 10.])

## **3.3 Random Arrays**


In [ ]:
np.random.random((2,4))

array([[0.58906551, 0.33836451, 0.23083844, 0.11230296],
       [0.25458186, 0.48635038, 0.68684923, 0.60832103]])

In [ ]:
np.random.randint(0,30,(4,3))

array([[ 9,  6, 18],
       [22, 29, 29],
       [ 6, 28, 27],
       [26, 14, 12]])

In [ ]:

np.random.randn(10)    # standard normal distribution

array([-0.78417359,  1.02996978,  0.7097122 , -0.49343141, -0.37691201,
       -0.4739835 , -0.49164178, -1.34179066, -0.74605146, -0.41954549])

# 📘 **4. Indexing & Slicing in NumPy**

## **4.1 Basic Indexing**

In [ ]:
a = np.array([10, 20, 30, 40, 50])
    # first element
a[0]

np.int64(10)

In [ ]:
  # last element
a[-1]

np.int64(50)

In [ ]:
# elements from index 1 to 3
a[1:4]

array([20, 30, 40])

In [ ]:
    # first 3
a[0:4]

array([10, 20, 30, 40])

In [ ]:
a[:4]

array([10, 20, 30, 40])

In [ ]:
    # from index 2 to end
a[2::-1]

array([30, 20, 10])

## **4.2 Slicing**


## **4.3 2D Indexing**

In [ ]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

  # row 0, col 1
b[0][1]

np.int64(2)

In [ ]:
b[0,1]

np.int64(2)

In [ ]:
 # column 1
b[:,1]

array([2, 5, 8])

**Array 2-Dim indexing syntax:**

`array[start_row_index:end_row_index,start_col_index:end_col_index]`

In [ ]:
  # row 1
b[1,:]

array([4, 5, 6])

In [ ]:
# print from 0to 1 row and 1 to 2nd col

b[0:1,1:3]

array([[2, 3]])


# 📗 **5. Array Operations**

## **5.1 Element-wise Arithmetic**

In [ ]:
l1=(2,4)
l2=(1,6)
l1+l2

(2, 4, 1, 6)

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x+y

array([5, 7, 9])

In [ ]:
x-y

array([-3, -3, -3])

In [ ]:
x%y

array([1, 2, 3])

In [ ]:
x//y


array([0, 0, 0])

In [ ]:
x**3


array([ 1,  8, 27])

In [ ]:
x*y

array([ 4, 10, 18])


## **5.2 Scalar Operations**

In [ ]:
x+10


array([11, 12, 13])

In [ ]:
x*3

array([3, 6, 9])

## **5.3 Broadcasting**

In [ ]:
arr1

array([2.340e+01, 5.000e+00, 3.800e+00, 5.330e+02, 8.953e+03])

In [ ]:
arr1 +np.array([1,2,3,4,5])

array([2.440e+01, 7.000e+00, 6.800e+00, 5.370e+02, 8.958e+03])

# 📙 **6. Mathematical Functions**

In [ ]:
x

array([1, 2, 3])

In [ ]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.exp(x)


array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.log(x)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.sin(x)

array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
np.cos(x)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [ ]:
np.mean(x)

np.float64(2.0)

In [ ]:
np.std(x)

np.float64(0.816496580927726)

In [ ]:
np.median(x)


np.float64(2.0)

In [ ]:
np.sum(x)


np.int64(6)

In [ ]:
np.min(x)


np.int64(1)

In [ ]:
np.max(x)

np.int64(3)

# 📘 **7. Boolean Masks & Filtering**

In [ ]:
a = np.array([10, 20, 30, 40, 50])
mask=a>20
a[mask]

array([30, 40, 50])

In [ ]:
#Shortcut:
a[a>20]


array([30, 40, 50])

# 📗 **8. Reshaping & Flattening**

## **8.1 Reshape**

In [ ]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr.reshape((6,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

## **8.2 Flatten / Ravel**

In [ ]:
reshap_arr=arr.reshape(3,4)
reshap_arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# 📙 **9. Stacking**

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
## **Vertical & Horizontal**
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

# 📘 **10. Copy vs View**

## **View (shares memory)**


In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
b=a.view()
a[0]=100
a

array([100,   1,   2,   3,   4])

In [ ]:
b

array([100,   1,   2,   3,   4])

## **Copy (independent)**

In [ ]:
c=a.copy()
a[1]=200
a

array([100, 200,   2,   3,   4])

In [ ]:
c

array([100,   1,   2,   3,   4])

# 📙 **11. Useful Utility Functions**

In [ ]:
    # returns indices
np.unique([1,3,1,5])

array([1, 3, 5])

In [ ]:
np.sort([34,25,1])

array([ 1, 25, 34])

In [ ]:
np.argsort([23,1,67])

array([1, 0, 2])

# 📗 **12. Linear Algebra**

In [ ]:
A = np.array([[1,2],[3,4]])
b = np.array([5,6])

np.dot(A, b)


array([17, 39])

In [ ]:
np.linalg.inv(A)


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.linalg.det(A)


np.float64(-2.0000000000000004)

In [ ]:
np.linalg.eig(A)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

# 🧪 **Practice Exercises**

## **Exercise 1**

Create a 1D array of numbers 1–20 and extract:

* elements greater than 10
* every 3rd element
* reverse the array

## **Exercise 2**

Create a 3×3 matrix of random integers from 1–100 and compute:

* row-wise mean
* column-wise sum
* overall standard deviation

## **Exercise 3**

Given a 1D array: `arr = np.array([3,6,9,12,15])`
Compute:

* square of each element
* log values
* normalized version (subtract mean & divide by std)

---
